contractslist/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import ContractsInfoView, ContractsListView, ContractDetail, DisplayPdfView, \
    SearchResultsView, ContractUpdateView, ContractCreateView

urlpatterns = [
    path('', ContractsInfoView.as_view(), name='index'),
    path('list/', ContractsListView.as_view(), name='contract-list'),
    path('list/pdf/<int:pk>/', DisplayPdfView.as_view(), name='con-pdf-view'),
    path('list/detail/<int:pk>/', ContractDetail.as_view(), name='contract-detail'),
    # path('dop/', ContractDopListView.as_view(), name='contract-dop-list'),
    # path('dops/', DopSListView.as_view(), name='dop-list'),
    # path('dops/pdf/<int:pk>/', DisplayPdfView.as_view(), name='dop-pdf-view'),
    # path('dops/detail/<int:pk>/', DopDetail.as_view(), name='dop-detail'),
    path('search/', SearchResultsView.as_view(), name='search-results'),
    path('update/<int:pk>', ContractUpdateView.as_view(), name='contract-update'),
    path('create/', ContractCreateView.as_view(), name='contract-create'),
]
# только в режиме DEBUG для Upload
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


class TypeDoc(models.Model):
    """ Тип документа: госконтракт или допсоглашение """
    name = models.CharField(max_length=100, unique=True, db_index=True, verbose_name='Документ')

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = "Документ"
        verbose_name_plural = "Документы"
        ordering = ('name',)  # сортировка


class Initiator(models.Model):
    """ Инициаторы закупки"""
    name = models.CharField(max_length=100, unique=True, db_index=True, verbose_name='Инициатор')

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = "Инициатор"
        verbose_name_plural = "Инициаторы"
        ordering = ('name',)  # сортировка


class StatusContract(models.Model):
    """ Статус контракта """
    name = models.CharField(max_length=50, unique=True, db_index=True, verbose_name='Наименование')

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"
        ordering = ('name',)  # сортировка


class Contracts(models.Model):
    """ Реестр контрактов """
    # num_izv = models.CharField(max_length=20, db_index=True, verbose_name='Номер извещения', default='-')
    # nc_contract = models.CharField(max_length=30, db_index=True, verbose_name='Номер карточки контракта', default='-')
    num_contract = models.CharField(max_length=20, db_index=True, verbose_name='Номер контракта', default='-')
    name_object = models.CharField(max_length=500, db_index=True, verbose_name='Наименование объекта закупки',
                                   default='-')
    type_doc = models.ForeignKey(TypeDoc, on_delete=models.DO_NOTHING, verbose_name='Документ', default='-')
    y_contract = models.CharField(max_length=4, verbose_name='Год', default='1970')
    # nmck = models.FloatField(max_length=50, verbose_name='НМЦ')
    c_contract = models.FloatField(max_length=50, verbose_name='Цена контракта')
    # econom = models.FloatField(max_length=50, verbose_name='Экономия')
    # proc_econom = models.FloatField(max_length=6, verbose_name='Процент экономии')
    ini_contract = models.ForeignKey(Initiator, on_delete=models.DO_NOTHING, verbose_name='Инициатор', default='-')
    uch_contract = models.CharField(max_length=200, db_index=True, verbose_name='Участник', default='-')
    in_contract = models.CharField(max_length=10, null=True, verbose_name='Дата подписания контракта')
    in_work = models.CharField(max_length=10, null=True, verbose_name='Дата начала работ')
    out_work = models.CharField(max_length=10, null=True, verbose_name='Дата окончания работ')
    stat_contract = models.ForeignKey(StatusContract, on_delete=models.DO_NOTHING, verbose_name='Статус', default='-')
    work_contract = models.BooleanField('В работе')
    failures = models.BooleanField('Срыв сроков')
    executed = models.BooleanField('Исполнен')
    file_obj = models.FileField(upload_to='files/')
    data_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.num_contract

    class Meta:
        verbose_name = "Госконтракт"
        verbose_name_plural = "Госконтракты"
        ordering = ('y_contract', 'num_contract',)  # сортировка

# class FileContract(models.Model):
#     #
#     file_obj = models.FileField(upload_to='files/')

main/forms.py
from django import forms
from .models import Contracts


class ContractForm(forms.ModelForm):
    """Форма"""
    class Meta:
        model = Contracts
        #fields = ['nregion', 'iroad', 'troad', 'innroad', 'inroad','proad']
        fields = '__all__' #все поля
        # exclude = ['n'] #должны быть исключены из формы
        # help_texts = {
        #     'nregion': (' - Название района.'),
        #     'lroad': (' км'),
        # }


class ContractCreatForm(forms.ModelForm):
    """Форма"""

    class Meta:
        model = Contracts
        # fields = ['nregion', 'iroad', 'troad', 'innroad', 'inroad','proad']
        fields = '__all__'  # все поля
        # fields = ['file_obj']

main/views.py
import datetime
import os
import django_filters

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.contrib import messages
from django.db.models import Sum, Count, Q
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django.views.generic.base import View
from django.views.generic.detail import BaseDetailView
from .forms import ContractCreatForm, ContractForm
# пагинация
from django.shortcuts import render, get_object_or_404

from .models import Contracts
from django.http import FileResponse, Http404


class ContractsInfoView(View):
    """ Сводная информация на главной странице """

    # def get(self, request, *args, **kwargs):
    @staticmethod
    def get(request):
        # рабочие контракты без допов
        info = Contracts.objects.all().filter(work_contract=True).exclude(type_doc=3).aggregate(
            Count('id', distinct=True), Sum('c_contract'))
        qs = Contracts.objects.all().filter(work_contract=True, type_doc=1)
        d_today = datetime.date.today()
        summ_ost = 0
        for rw in qs:
            summ_ost += rw.c_contract
        info['ogk__sum'] = summ_ost
        info['date__today'] = d_today
        return render(request, 'index.html', context=info)


class ContractsListView(ListView):
    """ Перечень контрактов для просмотра """
    model = Contracts
    # рабочие контракты без КС
    queryset = Contracts.objects.all().filter(work_contract=True).exclude(type_doc=3)

    template_name = 'main/contract_list.html'
    paginate_by = 5


class ContractDetail(DetailView):
    """ Информация о контракте """
    model = Contracts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d_today = datetime.date.today()
        context['d_today'] = d_today
        # period = kwargs['object'].period
        # broad = kwargs['object'].broad
        # oroad = kwargs['object'].oroad
        # am_month = ammort(period, broad)
        # summ_ost = oroad - am_month * d_today.month
        context['summ_ost'] = 666
        objkey = self.kwargs.get('pk', None)
        c_num = Contracts.objects.filter(work_contract=True, id=objkey).exclude(type_doc=3)
        # context['dops'] = Contracts.objects.filter(work_contract=True, type_doc=2, num_contract=c_num)
        # if self.request.user.is_authenticated:
        #     return context
        # else:
        #     return Contracts.objects.none()
        return context


class DisplayPdfView(BaseDetailView):
    """ Вывод на экран скана контракта в формате PDF"""

    def get(self, request, *args, **kwargs):
        objkey = self.kwargs.get('pk', None)  # обращение к именованному аргументу pk, переданному по URL-адресу
        pdf = get_object_or_404(Contracts, id=objkey)  # Эта строка получает фактический объект модели pdf
        # if pdf.type_doc_id == 1:
        # file_name = pdf.y_contract + '\\' + pdf.num_contract + '.pdf'  # Папка год + имя файла + расширение
        file_name = pdf.y_contract + '\\' + str(pdf.file_obj)  # Папка год + имя файла
        # else:
        #     file_name = pdf.y_contract + '\\' + pdf.num_contract + '.' + pdf.name_object + '.pdf'
        # Папка год + имя файла + расширение
        path = os.path.join(settings.MEDIA_ROOT, file_name)  # полный путь к файлу
        response = FileResponse(open(path, 'rb'), content_type="application/pdf")
        response["Content-Disposition"] = "filename={}".format(file_name)
        return response


class SearchResultsView(View):
    template_name = 'main/search_results.html'

    # @login_required
    def get(self, request, *args, **kwargs):
        context = {}

        question = request.GET.get('q')
        if question is not None:  # поиск по номеру, названию и усастнику
            search_contracts = Contracts.objects.filter(
                Q(num_contract__icontains=question) |
                Q(name_object__icontains=question) |
                Q(uch_contract__icontains=question))

            # формируем строку URL, которая будет содержать последний запрос
            # Это важно для корректной работы пагинации
            context['last_question'] = '?q=%s' % question

            current_page = Paginator(search_contracts, 3)

            page = request.GET.get('page')
            try:
                context['contract_lists'] = current_page.page(page)
            except PageNotAnInteger:
                context['contract_lists'] = current_page.page(1)
            except EmptyPage:
                context['contract_lists'] = current_page.page(current_page.num_pages)

        return render(None, template_name=self.template_name, context=context)


class ContractUpdateView(UpdateView):
    """Внесение изменений"""
    model = Contracts
    form_class = ContractForm
    success_url = reverse_lazy('contract-list')

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Contracts.objects.all()
        else:
            return Contracts.objects.none()

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(
            self.request, '{}'.format(form.instance))
        return result


class ContractCreateView(CreateView):
    """Заполнение аттрибутов контракта"""
    model = Contracts
    form_class = ContractCreatForm
    success_url = reverse_lazy('contract-list')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(
            self.request, '{}'.format(form.instance))
        return result

templates/main/contract_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 class="mb-3">Государственный контракт: &nbsp; </h1>
        <div class="card mb-1">
{% comment %}            <p class="card-header"><strong>Район : &nbsp; {{ road.nregion }}</strong></p>
            <p class="card-header"><strong>Тип дороги : &nbsp; {{ road.troad }}</strong></p>
            <p class="card-header"><strong>Протяженность : &nbsp; {{ road.lroad }} км </strong></p>
            <p class="card-header"><strong>Стоимость на {{ d_today }} : </strong></p>
            <p class="card-header">&nbsp;&nbsp;&nbsp; Балансовая : {{ road.broad }} руб. </p>
            <p class="card-header">&nbsp;&nbsp;&nbsp; Остаточная : {{ summ_ost }} руб. </p>
{% endcomment %}
        </div><br><hr>
    <div class="card-header">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-2"><a href="#" class="btn btn-sm btn-outline-info my-2 my-sm-0" aria-disabled="true">Показатели контракта</a></div>
            <div class="col-3"><a href="{% url 'contract-list' %}" class="btn btn-outline-success my-1 my-sm-0" aria-disabled="true">Перечень контрактов</a></div>
        </div>
    </div>
{% endblock content %}

templates/main/contract_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    {% if user.is_authenticated %}
      <h2 class="mb-3">Государственный контракт : </h2>
      <h5>{{ road.nroad }}</h5>
      <form method="post">
        <div class="card-header">
          <div class="row">
            <div class="col-12">
              {{ form|crispy}}
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <button class="btn btn-outline-primary">Сохранить</button>
                <a href="{% url 'contract-list' %}" class="btn btn-outline-success my-1 my-sm-0">Отмена</a>
            </div>
          </div>
        </div>
        {% csrf_token %}
      </form>
    {% else %}
        <h2 class="mb-3">Зарегистрируйтесь!!!</h2>
    {% endif %}
{% endblock %}

templates/main/contract_list.html
{% extends "base.html" %}

{% block content %}
<h2 class="mb-3">Перечень контрактов :</h2><hr>
    {% for contract in contracts_list %}
        <div class="card-header">
            <div class="row">
                <div class="col-md-6" >
                    {% if contract.type_doc.id == 1 %}
                        <h5> № {{ contract.num_contract }}  ,  Цена: {{ contract.c_contract}}</h5><br>
                        <h5> {{ contract.name_object }} </h5>
                    {% else %}
                        <h7> № {{ contract.num_contract }}  ,  Цена: {{ contract.c_contract}}</h7><br>
                        <h7> {{ contract.name_object }} </h7>
                    {% endif %}
                </div>
                {% if user.is_authenticated %}
                    <div class="col-md-2"><a href="{% url 'contract-detail' contract.id %}" class="btn btn-sm btn-outline-info my-2 my-sm-0" role="group" aria-disabled="true">Просмотр</a></div>
                    <div class="col-md-2"><a href="{% url 'con-pdf-view' contract.id %}" class="btn btn-sm btn-outline-info my-2 my-sm-0" role="group" aria-disabled="true">ПДФ</a></div>
                    <div class="col-md-2"><a href="{% url 'contract-update' contract.id %}" class="btn btn-sm btn-outline-danger my-2 my-sm-0" role="group" aria-disabled="true">Изменить</a></div>
                {% else %}
                    <div class="col-md-2"><a href="{% url 'contract-detail' contract.id %}" class="btn btn-sm btn-outline-info my-2 my-sm-0" role="group" aria-disabled="true">Просмотр</a></div>
                    <div class="col-md-2"></div>
                {% endif %}

            </div>
        </div>

    {% empty %}
        <h1>Список пуст!</h1>
    {% endfor %}

        {% if user.is_authenticated %}
            <br>
                <div class="row">
                    <div class="col"><a href="{% url 'contract-create' %}" class="btn btn-outline-danger my-1 my-sm-0" aria-disabled="true">Создать</a></div>
                </div><br>
        {% endif %}

    {% block pagination %}
        {% if is_paginated %}

            {% load bootstrap4 %}
            {% bootstrap_pagination page_obj %}

        {% endif %}
    {% endblock pagination%}

{% endblock content %}

templates/main/contracts_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1 class="mb-3">Государственный контракт: № &nbsp;{{ contracts.num_contract }}</h1>
        <div class="card mb-1">

            <p class="card-header"><strong>Наименование объекта : &nbsp; {{ contracts.name_object }}</strong></p>
            <p class="card-header"><strong>Подрядчик : &nbsp; {{ contracts.uch_contract }} </strong></p>
            <p class="card-header"><strong>Дата начала работ : &nbsp; {{ contracts.in_work }} г.</strong></p>
            <p class="card-header"><strong>Дата окончания работ : &nbsp; {{ contracts.out_work }} г.</strong></p>
            <p class="card-header"><strong>Дополнительные соглашения :</strong></p>
{% comment %}             {% for dop in dops %}
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6" >
                            <h6></h6>
                        </div>

                    </div>
                </div>
            {% empty %}
                <h1>Список пуст!</h1>
            {% endfor %}
            <br>
            <p class="card-header"><strong>по состоянию на {{ d_today }} </strong></p>
            <br>

{% comment %}            <p class="card-header">&nbsp;&nbsp;&nbsp; Балансовая : {{ road.broad }} руб. </p>
            <p class="card-header">&nbsp;&nbsp;&nbsp; Остаточная : {{ summ_ost }} руб. </p>
{% endcomment %}
        </div><br><hr>
    <div class="card-header">
        <div class="row">
            <div class="col-md-4"><a href="{% url 'contract-list' %}" class="btn btn-outline-success my-2 my-sm-0" aria-disabled="true">Перечень контрактов</a></div>
        </div>
    </div>
{% endblock content %}

templates/main/contracts_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if user.is_authenticated %}
      <h2 class="mb-3">{{ contracts.type_doc }} : </h2>
      <h5>{{ contracts.name_object }}</h5>
      <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="card-header">
          <div class="row">
            <div class="col-12">
              {{ form|crispy}}
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-12">
              <button class="btn btn-outline-primary">Сохранить</button>
              <a href="{% url 'contract-list' %}" class="btn btn-outline-success my-1 my-sm-0">Отмена</a>
            </div>
          </div>
        </div>
      </form>
    {% else %}
        <h2 class="mb-3">Зарегистрируйтесь!!!</h2>
    {% endif %}
{% endblock %}

templates/main/display_pdf_view.html
{% extends "base.html" %}

{% block content %}

{% endblock content %}

templates/main/search_results.html
{% extends "base.html" %}

{% block content %}
<h2 class="mb-3">Результат поиска :</h2><hr>
    {% if contract_lists %}
        {% for contract in contract_lists %}

            <div class="card-header">
                <div class="row">
                    <div class="col-md-6" >
                        <h6> № {{ contract.num_contract }}  ,  Цена: {{ contract.c_contract}}</h6><br>
                        <h6> {{ contract.name_object }} </h6>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="col-md-2"><a href="{% url 'contract-detail' contract.id %}" class="btn btn-sm btn-outline-info my-2 my-sm-0" role="group" aria-disabled="true">Просмотр</a></div>
                        <div class="col-md-2"><a href="{% url 'con-pdf-view' contract.id %}" class="btn btn-sm btn-outline-info my-2 my-sm-0" role="group" aria-disabled="true">ПДФ</a></div>
                        <div class="col-md-2"><a href="{% url 'contract-update' contract.id %}" class="btn btn-sm btn-outline-danger my-2 my-sm-0" role="group" aria-disabled="true">Изменить</a></div>
                    {% else %}
                        <div class="col-md-2"><a href="{% url 'contract-detail' contract.id %}" class="btn btn-sm btn-outline-info my-2 my-sm-0" role="group" aria-disabled="true">Просмотр</a></div>
                        <div class="col-md-2"></div>
                    {% endif %}

                </div>
            </div>
{% comment %}
        {% empty %}
            <h1>Список пуст!</h1>

{% endcomment %}

        {% endfor %}
        {% load bootstrap4 %}
        {% bootstrap_pagination contract_lists url=last_question %}
    {% else %}
        <p>Не найдено публикаций по вашему запросу<br>Попробуйте повторить запрос с другой формулировкой</p>
    {% endif %}

{% comment %}
    {% for contract in contracts_list %}

        <div class="card-header">
            <div class="row">
                <div class="col-md-6" >
                    <h6> № {{ contract.num_contract }}  ,  Цена: {{ contract.c_contract}}</h6><br>
                    <h6> {{ contract.name_object }} </h6>
                </div>
                {% if user.is_authenticated %}
                    <div class="col-md-2"><a href="{% url 'contract-detail' contract.id %}" class="btn btn-sm btn-outline-info my-2 my-sm-0" role="group" aria-disabled="true">Просмотр</a></div>
                    <div class="col-md-2"><a href="{% url 'con-pdf-view' contract.id %}" class="btn btn-sm btn-outline-info my-2 my-sm-0" role="group" aria-disabled="true">ПДФ</a></div>
                    <div class="col-md-2"><a href="{% url 'contract-update' contract.id %}" class="btn btn-sm btn-outline-danger my-2 my-sm-0" role="group" aria-disabled="true">Изменить</a></div>
                {% else %}
                    <div class="col-md-2"><a href="{% url 'contract-detail' contract.id %}" class="btn btn-sm btn-outline-info my-2 my-sm-0" role="group" aria-disabled="true">Просмотр</a></div>
                    <div class="col-md-2"></div>
                {% endif %}

            </div>
        </div>

    {% empty %}
        <h1>Список пуст!</h1>
    {% endfor %}

        {% if user.is_authenticated %}
            <br>
                <div class="row">
                    <div class="col"><a href="{% url 'contract-create' %}" class="btn btn-outline-danger my-1 my-sm-0" aria-disabled="true">Создать</a></div>
                </div>
            <br>
        {% endif %}

    {% block pagination %}
        {% if is_paginated %}

            {% load bootstrap4 %}
            {% bootstrap_pagination page_obj %}

        {% endif %}
    {% endblock pagination%}
{% endcomment %}

{% endblock content %}